frontend/src/components/AssetPrice.vue
frontend/src/views/Charts.vue
frontend/src/views/Details.vue

Stock price component

---

backend/src/server.ts
common/models/objectUtils.ts
frontend/src/components/Charts/CandlestickChart.vue
frontend/src/components/Header.vue
frontend/src/components/SearchBar.vue
frontend/src/views/Details.vue

Search bar improvements

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/AssetPrice.vue
frontend/src/views/Details.vue

This calculates the total and percentage change between 2 given money objects inside the AssetPrice component.
This could possibly be used to display changes between different time ranges.

Asset price improvements

---

common/package.json
frontend/src/components/Charts/CandlestickChart.vue

improve radio button styling

---

frontend/src/components/CompanyInfo.vue
frontend/src/components/DataField.vue
frontend/src/views/Details.vue

Add CompanyInfo and DataField components

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/CompanyInfo.vue
frontend/src/i18n.ts
frontend/src/locales/en.yml
frontend/src/main.ts
frontend/tsconfig.json
frontend/vite.config.js

I18n setup

---

backend/package-lock.json
common/models/base/BaseObject.ts
frontend/src/components/DataTable.vue
frontend/src/components/Sidebar.vue
frontend/src/router.ts
frontend/src/views/Transactions.vue

Add transaction table

---

frontend/src/components/DataTable.vue
frontend/src/locales/en.yml
frontend/src/views/Transactions.vue

Improve transactions table

---

common/models/Watchlist.ts
frontend/src/components/DataTable.vue
frontend/src/locales/en.yml
frontend/src/views/WatchlistsDetails.vue

Add dataTable to watchlistDetail

---

frontend/src/components/DataTable.vue
frontend/src/components/base/DataField.vue
frontend/src/components/base/SearchField.vue
frontend/src/locales/en.yml
frontend/src/styleguide/views/DataTables.vue
frontend/src/views/Transactions.vue
frontend/src/views/WatchlistsDetails.vue

I have currently handled the sorting in the DataTable component, but the filters and the search in the parent component.
This enables us to put filters wherever we want, so in this case inside the HeadlineActions component. But it might be a little unclear whats happening where.
I would further develop this when we have another page that needs search and filters and we want to reuse this functionality

Improve DataTables

---

.github/workflows/ci.yml
backend/.eslintrc.js
backend/package-lock.json
backend/package.json
common/Crypto/index.ts
common/package.json
common/utils.ts
frontend/.eslintrc.js
frontend/package.json
frontend/src/components/AssetSearch.vue
frontend/src/components/BuySellAsset.vue
frontend/src/components/DataTable.vue
frontend/src/components/SearchBar.vue
frontend/src/views/Transactions.vue
frontend/src/views/WatchlistsDetails.vue
frontend/tsconfig.json

this continues work from @sadortun on sadortun/split-search

Split search

---

.idea/codeStyles/Project.xml
frontend/src/components/DataTable.ts
frontend/src/components/DataTable.vue
frontend/src/utils/screens.ts
frontend/src/views/Holdings.vue
frontend/src/views/Transactions.vue
frontend/src/views/WatchlistsDetails.vue
frontend/tsconfig.json
frontend/vite.config.js

Table layout

---

.idea/codeStyles/codeStyleConfig.xml
.idea/i18nally.json
CHANGELOG.md
backend/src/cloud/Assets/liveQueries/AssetPrice.ts
common/src/models/Watchlist.ts
common/src/models/WatchlistItem.ts
frontend/src/components/AddToWatchlist.vue
frontend/src/components/AddWatchlist.vue
frontend/src/components/Transactions/ImportTransactionsModal.vue
frontend/src/components/WatchAssetModal.vue
frontend/src/components/base/ButtonDefault.vue
frontend/src/components/base/GEmptyState.vue
frontend/src/components/base/GoModal.vue
frontend/src/components/base/Private.vue
frontend/src/hooks/useWatchlist.ts
frontend/src/store/AssetPriceStore.ts
frontend/src/styleguide/views/Buttons.vue
frontend/src/styleguide/views/Modals.vue
frontend/src/types/index.ts
frontend/src/views/Watchlists.vue
frontend/src/views/WatchlistsDetails.vue

Fix Watchlists

---

common/src/models/Transaction.ts
frontend/src/components/EditCreateAccount.vue
frontend/src/components/Sidebar.vue
frontend/src/locales/en.yml
frontend/src/router.ts
frontend/src/views/Accounts.vue

Initial Account view.
Its missing a Currency select. Will be added in another PR

Accounts View

---

CHANGELOG.md
frontend/src/components/Transactions/CSVExporter.ts
frontend/src/components/Transactions/DefaultCSVImporter.ts
frontend/src/components/Transactions/ExportTransactionsModal.vue
frontend/src/components/Transactions/ImportTransactionsModal.vue
frontend/src/components/base/GDropdown.vue
frontend/src/components/base/GoModal.vue
frontend/src/locales/en.yml
frontend/src/store/TransactionStore.ts
frontend/src/views/Transactions.vue

resolves #686 
There is still an issue with the account name

Export csv

---

common/src/models/AssetProfile.ts
frontend/src/components/Analytics/KeyMetrics.vue
frontend/src/components/Analytics/TypeAllocationChart.vue
frontend/src/components/CompanyInfo.vue
frontend/src/components/base/DataField.vue
frontend/src/components/base/DataFormatter.vue
frontend/src/components/base/GHeadline.vue
frontend/src/components/base/GStatistic.vue
frontend/src/types/index.ts
frontend/src/views/Analytics.vue

Analytics metrics

---

.idea/GoPlan-app.iml
.idea/modules.xml
.idea/vcs.xml
backend/src/Migrations/schemas/HoldingSchema.ts
common/src/models/HoldingTimeSeries.ts
frontend/src/components/Charts/HoldingTimeSeriesChart.vue
frontend/src/components/Charts/useHoldingTimeSeries.ts
frontend/src/store/Holding/HoldingHelper.ts
frontend/src/store/Holding/HoldingHistoryHelper.ts
frontend/src/store/Holding/HoldingTimeSeriesHelper.ts
yarn.lock

Fix various bugs,
improved performance.

Updated Holding time series

---

common/src/models/Transaction.ts
frontend/src/components/AssetSearch.vue
frontend/src/components/BuySellAsset.vue
frontend/src/components/TransactionModal.vue
frontend/src/components/TransactionTypeSelect.vue
frontend/src/components/base/SearchField.vue
frontend/src/locales/en.yml
frontend/src/views/Analytics.vue
frontend/src/views/Details.vue
frontend/src/views/Holdings.vue
frontend/src/views/Transactions.vue

We still need to add deposit and withdraw logic to the balance calculation

Transaction Types

---

README.md

Added the OpenSSF Best practices badge. I completed the initial survey,  we still have many `?` and a few `Unmet` that are currently WIP.
Fix #677

Added OpenSSF Best practice badge

---

frontend/package.json
frontend/src/App.vue
frontend/src/components/NotificationDisplay.vue
frontend/src/components/TransactionModal.vue
frontend/src/components/base/GProgress.vue
frontend/src/store/NotificationStore.ts
frontend/src/store/index.ts
frontend/src/views/Transactions.vue
yarn.lock

Notifications
